### ISSUE TITLE
Need some more documentation on Custom button

### ISSUE THREAD

**Issue by annjawn** [dirtyredz/react-scroll-up-button#10]
Is there some example to demonstrate the usage of Custom react component inside the scroll up? I tried but it looks like the position gets messed up and I am not sure what CSS needs to be put in to fix it.

**Comment by dirtyredz** [comment]
```
import React from "react";
import ScrollUpButton from "react-scroll-up-button";

export default class Index extends React.Component {
    render() {
        return (
            <div>
                <ScrollUpButton ContainerClassName="ScrollUpButton__Container" TransitionClassName="ScrollUpButton__Toggled">
                    // Here you can add any react component or jsx
                    // ScrollButton will apply the classnames given to the container of whatever you put here.
                    // Changing appearence this way will only work when importing the default ScrollUpButton, importing any of the specific buttons do not except children
                </ScrollUpButton>
            </div>
        );
    }
}
```

You need to add a container class name and a transition class name, This will give you full control of the container its position and what that container should do when its transitioned.

**Comment by annjawn** [comment]
Thanks, I am using Semantic UI React, and I am trying to use a [SUIR Button ](https://react.semantic-ui.com/elements/button/)(which is a SUIR React component) inside of the ScrollUpButton. Like below. But I am having a hard time having the button show up on scroll.

```
<ScrollUpButton>
     <Button circular color='twitter' icon='angle double up'/>
 </ScrollUpButton>
```

I also did something like this. 

```
  .scroll-up-btn{
    bottom: 60px;
    right: 30px;
  }
```

```
<ScrollUpButton ContainerClassName="scroll-up-btn">
     <Button circular color='twitter' icon='angle double up'/>
 </ScrollUpButton>
```

The one thing that I did try and it kind of worked is below. Which is directly using [Semantic's](https://semantic-ui.com/elements/button.html) CSS. But this is just plain old CSS/LESS and I want to use the React JSX version as I show above

```
<ScrollUpButton ContainerClassName="circular ui icon button">
```

**Comment by dirtyredz** [comment]
when usign a child inside of the scroll button component, it depends on css to control its container and transition.
the containerClassName needs to have css that pushes the button outside of the screen usually this works best:
```
.ScrollUpButton__Container{
 position: fixed;
  right: -60px;
}
```

you will then need to have a transition css also pull the container into the screen:
```
.ScrollUpButton__Toggled{
 right: 100px;
}
```

**Comment by dirtyredz** [comment]
```
<ScrollUpButton ContainerClassName="scroll-up-btn">
     <Button circular color='twitter' icon='angle double up'/>
 </ScrollUpButton>
```

```
.scroll-up-btn {
position: fixed;
right: -60px;
}
.toggled{
right: 100px;
}
```

**Comment by annjawn** [comment]
Yes, perfect. Worked like a charm..... Thanks much for the detailed explanation.

**Comment by dirtyredz** [comment]
NP, if you think the explanation on the read me could be changed please submit a pr, Im never been very good at righting documentation and any help would be appreciative. Thanks

**Comment by annjawn** [comment]
@dirtyredz sure will do.

**Comment by dirtyredz** [comment]
Ive added a little something to the demo site, tell me if this would have helped.
https://react-scroll-up-button.com/

im also planning to add a few toggles to express some of the other options/props for the component.

**Comment by annjawn** [comment]
Yup, perfect. Thats a lot helpful.
