### ISSUE TITLE
Remove prop-types from production build

### ISSUE THREAD

**Issue by smashercosmo** [dirtyredz/react-scroll-up-button#11]
This will make package size a bit smaller

**Comment by dirtyredz** [comment]
> Actually the better option would be to publish cjs and esm bundles, but without bundling external dependencies into them.

Does this PR do this, or is it only for adding rollup for cjs and esm support?
Havent had time to do a complete review of the changes as of yet.
Also I've personally never used rollup so this is a first for me.

**Comment by smashercosmo** [comment]
Yeah, actually I've never used rollup either) I just checked how react-router team does this.
