### ISSUE TITLE
How can I use custom up-arrow icon?

### ISSUE THREAD

**Issue by php7webmob** [dirtyredz/react-scroll-up-button#17]
I want to use custom up-arrow icon how can I do that? I don't see any prop that I can use to change the default arrow.

**Comment by dirtyredz** [comment]
You can view an example on the Demo site here: https://react-scroll-up-button.com/

basically anything you put inside the component as a child will be rendered as the button:

```
<ScrollUpButton
    ContainerClassName="AnyClassForContainer"
    TransitionClassName="AnyClassForTransition"
>
  <MyCustomReactComponent />
</ScrollUpButton>
```

**Comment by php7webmob** [comment]
That was easy! Thanks.
