### ISSUE TITLE
cannot change the css using ContainerClassName="ScrollUpButton__Container"

### ISSUE THREAD

**Issue by czsyjss** [dirtyredz/react-scroll-up-button#3]
For example, if I write 

`render() {
        return (
            <div>
                <ScrollUpButton ContainerClassName="ScrollUpButton__Container" />
            </div>
        );
    }`

And in css

`
.ScrollUpButton__Container{
      bottom: 60px;
}
`
The bottom is still 20px as default.
Could anybody help me? Thank you so much.

**Comment by dirtyredz** [comment]
the Class name is not applied to the default view

"ContainerClassName -- Class name applied to the container when NOT using the default view.

TransitionClassName -- Class name applied to the container to show the button when NOT using the default view."

if you want to build a custom button then you need to add a component or jsx/html inside the componenet like so:

    <ScrollUpButton ContainerClassName="ScrollUpButton__Container" TransitionClassName="ScrollUpButton__Toggled">
        <span class="BTN">UP &#8594;</span>
    </ScrollUpButton>

**Comment by dirtyredz** [comment]
Added Override classname functionality to the default button. 62de48a

**Comment by czsyjss** [comment]
Thank you so much! @dirtyredz

**Comment by dirtyredz** [comment]
@czsyjss let me know if adding the class is enough, currently it does not remove the default styles applied to it so youll prolly need to use !important.
I struggle with deciding if i should stop the default styling on the default button when adding a class to it or force you to write your own button using the few examples ive provided.
