### ISSUE TITLE
Question: Choose when to show

### ISSUE THREAD

**Issue by muscaiu** [dirtyredz/react-scroll-up-button#5]
Is there any way to choose when to arrow should show based on how much you scrolled ?

Like for example i want the arrow to show when i scrolled 50% of the page.

**Comment by dirtyredz** [comment]
the `TransitionBtnPosition` property can be set to the Y scroll position of the page to apply the transition class.
Default is 150 px.

**Comment by felipe-pereira** [comment]
@dirtyredz looks like the readme (or the code) needs a small fix, since the option for this is `ShowAtPostion`

I found `ShowAtPostion` on the code but no `TransitionBtnPosition` so I'd update the readme file with this.

Most important; `ShowAtPostion` works as expected :)

**Comment by dirtyredz** [comment]
Wow i feel kinda silly that i missed that hehe.
