### ISSUE TITLE
Can't resolve 'babel-polyfill'

### ISSUE THREAD

**Issue by Justkant** [dirtyredz/react-scroll-up-button#6]
It's breaking my build.
I don't think that you should use [`babel-polyfill`](https://babeljs.io/docs/en/babel-polyfill) in a library.
I also commented in this commit https://github.com/dirtyredz/react-scroll-up-button/commit/8f13aa4bc174cb287c25bcc8d447fff4556e3300#r30672868

**Comment by Justkant** [comment]
As a library author you shouldn't care of polyfill or compatibility issues.
It's the user of the library that should include the polyfill needed for his use case.
You could however add an info in README to warn users that you need object.assign.
Also there is some tips in the Babel doc for the preset-env for libs

**Comment by dirtyredz** [comment]
It would also help if i was going to have babel-poly fill as a dependency to have that module in the dependencies, but i regress adding a module for a small poly fill is unnecessary.
Do you have a link to that documentation I have read present-env docs but not seen something about library authors, im sure im missing it but if you could provide a link I would much appreciate it.

**Comment by dirtyredz** [comment]
fixed ff4edac
I've replace babel-polyfill with object-assign.
In my opinion IE 11 support is necessary today, as IE 11 is still widely used.

**Comment by Justkant** [comment]
Yeah I didn't find the note for the library authors, maybe it was an issue..
object-assign should do the trick for you.
I also saw that you use the spread operator (e.g. for the props), why not use it to avoid using the object-assign directly ?
And because you compile using Babel you shouldn't need polyfills

**Comment by dirtyredz** [comment]
Thats actually a great point, ill look into that. This whole project has been a learning opportunity for me!!
