### ISSUE TITLE
GET data:image/png net::ERR_INVALID_URL

### ISSUE THREAD

**Issue by Cathaiste** [dirtyredz/react-scroll-up-button#8]
Hello, 

Upgrading from Gatsby v1 to Gatsby v2, I keep getting the error `GET data:image/png net::ERR_INVALID_URL` at react-scroll-up-button/dist/react-scroll-up-button.js:83. 

I don't get why I keep getting this error and I'm not able to do anything about it, so I'm asking for your help on this issue. 

![image](https://user-images.githubusercontent.com/26376521/46464276-3e735d00-c7c6-11e8-99ef-aa74fd7b5245.png)

The code where I use the plugin is the next: 
```
import React from 'react';
import {CircleArrow as ScrollUpButton} from 'react-scroll-up-button';

export default class Article extends React.component{
  render=()=>{
    return(
      <article>
            {/* ... */} 
            <ScrollUpButton ContainerClassName="ScrollUpButton__Container" TransitionClassName="ScrollUpButton__Toggled"/>
      </article>
    );
  }
}
```

And the last weird thing is that even with that error, the button still shows and works fine.
So, any idea on why that happens? Or am I in the wrong thinking it's the problem of the plugin?

Version of Gatsby: v2
Version of react-scroll-up-button: the latest (1.6.4)

**Comment by dirtyredz** [comment]
This is weird since ive used it one Gatsby v2 myself and that error message makes no sense, this repo doesn't use any images.

Does this happen only in develop mode or after building? or both?

**Comment by dirtyredz** [comment]
can you reproduce this using one of the gatsby starters?

**Comment by Cathaiste** [comment]
Hi, sorry about that, I might have been too fast on my judgement. After breaking down each components of my code, happened that it is not from this package, I am sorry I'm closing the issue

**Comment by dirtyredz** [comment]
Np, I'm glad you were able to figure it out.
